[workspace]
members = ["crates/api", "crates/sim-backend", "crates/worker"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.98"
async-trait = "0.1.89"
axum = { version = "0.8.4", features = ["ws"] }
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.6", features = [
  "runtime-tokio-rustls",
  "postgres",
  "chrono",
  "uuid",
  "json",
  "migrate",
] }
tokio = { version = "1.44.1", features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
  "signal",
] }
tokio-util = "0.7.15"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "fmt",
  "json",
] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }
