[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
sim-backend = { path = "../sim-backend" }
uuid.workspace = true
argon2 = "0.5.3"
jsonwebtoken = "9.3.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
tower-http = { version = "0.6.8", features = ["cors"] }
